# Site
name: "Unrestricted Info"
title: "Unrestricted Info"
description: "Information without the noise."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
disqus: 'unrestrictedinfo'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: PR
    display_name: pr
    avatar: /assets/images/avatar.png
    email: blah@gmail.com
    web: https://blog.unrestricted.info
    twitter: 
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
